### ISSUE TITLE
[BUG] AUR Build Fail with missing ECM

### ISSUE THREAD

**Issue by yuannan** [rbn42/panon#33]
**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version of Plasma Framework: 5.75.0-1

**Describe the bug**
AUR build fails with:
```
CMake Error at CMakeLists.txt:7 (find_package):
  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.
```
Fix:
extra-cmake-modules needed as depenency

**Comment by rbn42** [comment]
First, cmake is only required to build and install translations. And extra-cmake-modules is required by https://github.com/rbn42/panon/blob/stable/CMakeLists.txt, which is used by AUR build. Originally, I copied this cmakelist from Plasmoid's development tutorial. But I think we can discard this file, and use https://github.com/rbn42/panon/blob/stable/translations/CMakeLists.txt directly to build translations.
```bash
cd panon/translations/
mkdir build
cd build 
cmake ..
make install DESTDIR=~/.local/share/locale/ or /usr/share/locale/
```

@flying-sheep I see you updated v0.4.2 recently on AUR, Thanks. What do you think about issue? Because AUR build relies on that cmakelist to install panon, adding extra-cmake-modules as depenency would be the easier solution.

**Comment by flying-sheep** [comment]
If you change the way this is supposed to be built, I’ll change the PKGBUILD accordingly.

Most people should have `extra-cmake-modules` as it’s required to build most things KDE, but if panon is the only thing people ever build, not requiring it is a teensy tiny advantage.

**Comment by rbn42** [comment]
> If you change the way this is supposed to be built, I’ll change the PKGBUILD accordingly.

OK, I have changed it in `README.ORG`.

**Comment by flying-sheep** [comment]
Okay, I’ve subscribed to realeases, so hopefully I’ll see when you release. If not, please mark it as outdated in the AUR
